//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonEntitiesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinemas
    {
        public Cinemas()
        {
            this.Shows = new HashSet<Shows>();
        }
    
        public int CinemaId { get; set; }
        public string Name { get; set; }
        public int TownId { get; set; }
        public string Address { get; set; }
    
        public virtual Towns Towns { get; set; }
        public virtual ICollection<Shows> Shows { get; set; }
    }
}
