//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonEntitiesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genres
    {
        public Genres()
        {
            this.Movies = new HashSet<Movies>();
        }
    
        public int GenreId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
