//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.Shows = new HashSet<Shows>();
            this.Person1 = new HashSet<Person>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public int GenreId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int DirectorId { get; set; }
        public int ActorsId { get; set; }
        public int CountryId { get; set; }
        public string Description { get; set; }
        public string CoverLink { get; set; }
        public Nullable<bool> Subtitles { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shows> Shows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person1 { get; set; }
    }
}
