//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.Shows = new HashSet<Shows>();
            this.Person1 = new HashSet<Person>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public int GenreId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int Director { get; set; }
        public int Actors { get; set; }
        public int CountryId { get; set; }
        public string Description { get; set; }
        public string CoverLink { get; set; }
        public bool Subtitles { get; set; }
        public int DurationMinutes { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Shows> Shows { get; set; }
        public virtual ICollection<Person> Person1 { get; set; }
    }
}
