//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shows
    {
        public int ShowId { get; set; }
        public int CienemaId { get; set; }
        public int MovieId { get; set; }
        public System.DateTime StartTime { get; set; }
    
        public virtual Cinemas Cinemas { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
