//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public Movy()
        {
            this.Shows = new HashSet<Show>();
            this.People = new HashSet<Person>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public int GenreId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int Director { get; set; }
        public int Actors { get; set; }
        public int CountryId { get; set; }
        public string Description { get; set; }
        public string CoverLink { get; set; }
        public bool Subtitles { get; set; }
        public int DurationMinutes { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Show> Shows { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
