//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public Cinema()
        {
            this.Shows = new HashSet<Show>();
        }
    
        public int CinemaId { get; set; }
        public string Name { get; set; }
        public int TownId { get; set; }
        public string Address { get; set; }
    
        public virtual Town Town { get; set; }
        public virtual ICollection<Show> Shows { get; set; }
    }
}
